### ISSUE TITLE
KISSMVC errors

### ISSUE THREAD

**Issue by precursorca** [tuxudo/ms_office#5]
While using ms_office with MunkiReport 4.01 there were a ton of KISSMVC error causing clients to fail to report in properly to the database. E.g.
[Fri Jan 04 06:10:11.368027 2019] [php7:error] [pid 57509] [client 184.70.38.2:62904] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: ms_office in /Users/Shared/munkireport-php/system/kissmvc_core.php:463\\nStack trace:\\n#0 /Users/Shared/munkireport-php/system/kissmvc_core.php(463): PDO->prepare('SELECT * FROM `...', Array)\\n#1 /Users/Shared/munkireport-php/system/kissmvc_core.php(606): KISS_Model->prepare('SELECT * FROM `...')\\n#2 /Users/Shared/munkireport-php/system/kissmvc.php(253): KISS_Model->retrieveOne('serial_number=?', Array)\\n#3 /Users/Shared/munkireport-php/vendor/munkireport/ms_office/ms_office_model.php(54): Model->retrieve_record('D25P20KDF8J7')\\n#4 /Users/Shared/munkireport-php/app/controllers/report.php(198): Ms_office_model->__construct('D25P20KDF8J7')\\n#5 /Users/Shared/munkireport-php/system/kissmvc_core.php(88): munkireport\\\\controller\\\\report->check_in()\\n#6 /Users/Shared/munkireport-php/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO')\\n#7 /Users/Shared/munkireport-php/bootstrap/app.php(121): Engine->__construct(Array, 'show', 'in in /Users/Shared/munkireport-php/system/kissmvc_core.php on line 463

**Comment by tuxudo** [comment]
Make sure you run the migrations after installing the module in order for it to make the database tables.
