### ISSUE TITLE
License widget shows incorrect info

### ISSUE THREAD

**Issue by ofirgalcon** [tuxudo/ms_office#6]
The widget shows 15 365 licenses, but I have none.

![image](https://user-images.githubusercontent.com/16665880/60355533-8a0a0e80-99c6-11e9-875f-4b02153fc69a.png)

![image](https://user-images.githubusercontent.com/16665880/60355602-b9208000-99c6-11e9-8431-0d317e4dca79.png)

**Comment by tuxudo** [comment]
I'm not able to reproduce this. Is it still an issue?

**Comment by ofirgalcon** [comment]
The number of O365 licenses shown in Listing and Widget don't add up. In listing page I see about 100 but widget says 667

![image](https://user-images.githubusercontent.com/16665880/76034861-f9fa6c80-5f37-11ea-9a65-0d106d746dfb.png)

**Comment by ofirgalcon** [comment]
I just updated my module with your latest, let me see if it makes a difference. Mine was pretty old.

**Comment by tuxudo** [comment]
If it continues to be a problem, DM me a dump of your ms_office table

**Comment by tuxudo** [comment]
Closing issue, resolved
