### ISSUE TITLE
Office Version detection issue

### ISSUE THREAD

**Issue by trekkim** [tuxudo/ms_office#8]
Hi , 
i found issue in detection of Office ver. in  script ms_office.py

Script checking only com.microsoft.Office365.plist
but user can have this file com.microsoft.Office365V2.plist but not in script.

I updated location in ms_office.py
.# Check all users' home folders for Office 365 license
def o365_license_detect():
    o365_count = 0
    o365_detect = 0
    # Get all users' home folders
    cmd = ['dscl', '.', '-readall', '/Users', 'NFSHomeDirectory']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()
    # Check in all users' home folders for Office 365 license
    for user in output.split('\n'):
        if 'NFSHomeDirectory' in user and '/var/empty' not in user:
            userpath1 = user.replace("NFSHomeDirectory: ", "")+'/Library/Group Containers/UBF8T346G9.Office/com.microsoft.Office365.plist'
            userpath2 = user.replace("NFSHomeDirectory: ", "")+'/Library/Group Containers/UBF8T346G9.Office/com.microsoft.Office365V2.plist'
            userpath3 = user.replace("NFSHomeDirectory: ", "")+'/Library/Group Containers/UBF8T346G9.Office/com.microsoft.e0E2OUQxNUY1LTAxOUQtNDQwNS04QkJELTAxQTI5M0JBOTk4O.plist'
            userpath4 = user.replace("NFSHomeDirectory: ", "")+'/Library/Group Containers/UBF8T346G9.Office/e0E2OUQxNUY1LTAxOUQtNDQwNS04QkJELTAxQTI5M0JBOTk4O'
            if (os.path.exists(userpath1)) or (os.path.exists(userpath2)) or (os.path.exists(userpath3)) or (os.path.exists(userpath4)):
                o365_count = o365_count + 1
                o365_detect = 1
    return {"o365_license_count":o365_count,"o365_detected":o365_detect}

please check , i was not able create PR .

Thank you

**Comment by tuxudo** [comment]
Merged in with PR #9
